loading i915/ radeon from initramfs seems to introduce initialisation problems on few systems, revert it for now.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,13 +1,34 @@
 #! /bin/sh
 set -e
 
-# clean up eventually left over /usr/sbin/policy-rc.d, which might not have
-# been cleaned up correctly by fll-installer << 0.5.12.
-if [ -f /usr/sbin/policy-rc.d ] && \
-   [ -z "$(dpkg-divert --list /usr/sbin/policy-rc.d)" ] && \
-   [ "x$(md5sum -b /usr/sbin/policy-rc.d | awk '{print $1}')" = "x2f31905d39c6a4ed28a9217decbb7208" ]; then
-	rm -f /usr/sbin/policy-rc.d
-fi
+case "$1" in
+	configure)
+		# clean up eventually left over /usr/sbin/policy-rc.d, which
+		# might not have been cleaned up correctly by 
+		# fll-installer << 0.5.12.
+		if [ -f /usr/sbin/policy-rc.d ] && \
+		   [ -z "$(dpkg-divert --list /usr/sbin/policy-rc.d)" ] && \
+		   [ "x$(md5sum -b /usr/sbin/policy-rc.d | awk '{print $1}')" = "x2f31905d39c6a4ed28a9217decbb7208" ]; then
+			rm -f /usr/sbin/policy-rc.d
+		fi
+
+		# recover from ill fated attempt to load i915/ radeon from 
+		# initramfs
+		if [ -x /usr/sbin/update-initramfs ] && \
+		   [ -e /etc/initramfs-tools/initramfs.conf ]; then
+			update-initramfs -u
+		fi
+		;;
+
+	abort-upgrade|abort-remove|abort-deconfigure)
+		:
+		;;
+
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+		;;
+esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
